CREATE DATABASE Practice;

CREATE TABLE Person(
	SNO INT AUTO_INCREMENT,
	PNAME VARCHAR(50) NOT NULL,
	AGE INT,
	ADDRESS VARCHAR(50)
	);
INSERT INTO PERSON(SNO,PNAME,AGE,ADDRESS) VALUES
	(1,'RAJKUMAR',24,'KRISHNAGIRI'),
	(2,'JAGAN',26,'KRISHNAGIRI'),
	(3,'SIVA ANBU',24,'KRISHNAGIRI'),
	(4,'SWETHA',24,'KRISHNAGIRI'),
	(5,'ARUL',22,'KRISHNAGIRI');

SELECT * FROM Person;	

UPDATE Person SET AGE=21 WHERE PNAME='ARUL';

DELETE FROM Person WHERE PNAME='ARUL';

SELECT DISTINCT AGE FROM Person;

SELECT * FROM Person ORDER BY PNAME DESC; 

SELECT * FROM Person WHERE PNAME='RAJKUMAR' AND AGE=24;

CREATE TABLE City(
	SNO INT,
	AREA VARCHAR(50)
	);

INSERT INTO City(SNO,AREA) VALUES
	(1,'KRISHNAGIRI'),
	(2,'SALEM'),
	(7,'SALEM')

SELECT P.SNO,P.PNAME,P.AGE,C.AREA FROM Person P LEFT JOIN CITY C ON P.SNO=C.SNO WHERE PNAME='RAJKUMAR';
